name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Install packages
      run: sudo apt-get update && sudo apt-get install -y git nano build-essential git subversion gfortran mpich libhdf5-serial-dev libfftw3-dev libgsl0-dev libssl-dev liblapack-dev hdf5-tools ccache pkg-config texlive-latex-extra tex4ht locales
      
    - name: Download GetComponents
      run: |
        curl -kLO https://raw.githubusercontent.com/gridaphobe/CRL/master/GetComponents
        chmod a+x GetComponents
        
    - name: Download toolkit
      run: ./GetComponents --parallel https://bitbucket.org/einsteintoolkit/manifest/raw/master/einsteintoolkit.th
      
    - name: Build and run the toolkit
      run: |
        cd Cactus
        simfactory/bin/sim setup-silent
        simfactory/bin/sim build -j2 --thornlist ../einsteintoolkit.th
        simfactory/bin/sim create-run helloworld --parfile arrangements/CactusExamples/HelloWorld/par/HelloWorld.par
